package cli

import (
	"database/sql"
	"math"
	"strconv"
	"strings"
	"time"
)

// Pattern candidate discovery (V2, Phase 3).
//
// Multi-family candidates generated by querying the corpus, replacing the
// single flat-file task model. A candidate is a corroborated recurring pattern —
// intent + method + evidence + outcome — not a bare command shape. The
// PROMOTION gate is the core fix over v1: a generic workflow (low command
// specificity) cannot cross the dossier threshold without repo-specific
// corroboration (a linked durable fact, a validation, or a recorded failure).
//
// Families: procedure (diagnostic command shapes), task (intent+method),
// practice (way-of-working + facts), risk (corrected/failed work). Workspace and
// theme families are deferred to later slices. Stored in patterns +
// pattern_evidence; rebuilt from the corpus on every refresh.

const (
	candidateMinSupport = 3
	promotionThreshold  = 0.65
	// A task only promotes if its command shape is itself non-generic. This is
	// what keeps generic git/review loops out of the promotable set even when an
	// episode incidentally touched a file we hold a fact about — that knowledge
	// belongs in a practice/risk, not a "commit" task.
	promotionSpecFloor = 0.35
)

// buildPatternCandidates rebuilds the patterns/pattern_evidence tables from the
// freshly-indexed corpus. Deterministic; runs inside the corpus build.
func buildPatternCandidates(db *sql.DB, repoKey string, now time.Time) error {
	if _, err := db.Exec(`DELETE FROM patterns`); err != nil { // cascades pattern_evidence
		return err
	}
	corpusN := corpusScalar(db, `SELECT COUNT(*) FROM episodes WHERE n_cmds > 0`)
	if corpusN == 0 {
		return nil
	}
	commandDF := loadCommandDF(db)
	ts := now.UTC().Format(time.RFC3339)

	for _, fam := range []func(*sql.DB, string, map[string]int, int, string) error{
		insertTaskCandidates,
		insertProcedureCandidates,
		insertRiskCandidates,
		insertPracticeCandidates,
	} {
		if err := fam(db, repoKey, commandDF, corpusN, ts); err != nil {
			return err
		}
	}
	// Consolidate promotable patterns into dossiers (deterministic, token-free).
	// The optional agent verifier runs only through explicit maintenance surfaces.
	return buildDossiers(db, repoKey, now)
}

func insertTaskCandidates(db *sql.DB, repoKey string, commandDF map[string]int, corpusN int, ts string) error {
	rows, err := db.Query(`
		SELECT e.intent_sig, g.gram,
		       COUNT(DISTINCT e.id),
		       COUNT(DISTINCT e.repo_key), COUNT(DISTINCT e.author_name), COUNT(DISTINCT e.branch),
		       SUM(e.outcome='success'), SUM(e.outcome='corrected'), SUM(e.outcome='failed'),
		       MAX(e.created_at),
		       MAX(CASE WHEN EXISTS(SELECT 1 FROM episode_facts ef WHERE ef.episode_id=e.id AND ef.weight >= 2) THEN 1 ELSE 0 END),
		       MAX(CASE WHEN EXISTS(SELECT 1 FROM meta_hits mh WHERE mh.episode_id=e.id AND mh.meta_id='validation_loop') THEN 1 ELSE 0 END),
		       MAX(CASE WHEN e.exit_fails>0 THEN 1 ELSE 0 END)
		FROM episodes e JOIN grams g ON g.episode_id = e.id
		WHERE e.intent_sig != '' AND e.n_cmds > 0
		GROUP BY e.intent_sig, g.gram
		HAVING COUNT(DISTINCT e.id) >= ?`, candidateMinSupport)
	if err != nil {
		return err
	}
	defer rows.Close()
	for rows.Next() {
		var (
			intentSig, gram, lastSeen                    string
			support, repos, authors, branches            int
			succ, corr, fail, hasFact, hasValid, hasFail int
		)
		if err := rows.Scan(&intentSig, &gram, &support, &repos, &authors, &branches, &succ, &corr, &fail, &lastSeen, &hasFact, &hasValid, &hasFail); err != nil {
			return err
		}
		spec := gramSpecificity(gram, commandDF, corpusN)
		corroborated := hasFact == 1 || hasValid == 1 || hasFail == 1
		score := taskScoreV2(support, spec, succ, corr, fail, repos, authors, branches, lastSeen)
		// Promote only a specific, corroborated task — generic command shapes stay
		// diagnostic regardless of incidental fact links.
		score = applyPromotionGate(score, corroborated && spec >= promotionSpecFloor)
		cluster := "task:" + intentSig + "\x00gram:" + gram
		title := intentSig + " — " + gram
		if err := insertPattern(db, "task", repoKey, cluster, title, intentSig, gram, score, support, repos, authors, branches, succ, corr, fail, ts); err != nil {
			return err
		}
	}
	return rows.Err()
}

func insertProcedureCandidates(db *sql.DB, repoKey string, commandDF map[string]int, corpusN int, ts string) error {
	rows, err := db.Query(`
		SELECT g.gram, COUNT(DISTINCT g.episode_id),
		       COUNT(DISTINCT e.repo_key), COUNT(DISTINCT e.author_name), COUNT(DISTINCT e.branch),
		       SUM(e.outcome='success'), SUM(e.outcome='corrected'), SUM(e.outcome='failed'), MAX(e.created_at),
		       MAX(CASE WHEN EXISTS(SELECT 1 FROM episode_facts ef WHERE ef.episode_id=e.id) THEN 1 ELSE 0 END)
		FROM grams g JOIN episodes e ON e.id = g.episode_id
		GROUP BY g.gram
		HAVING COUNT(DISTINCT g.episode_id) >= ?`, candidateMinSupport)
	if err != nil {
		return err
	}
	defer rows.Close()
	for rows.Next() {
		var (
			gram, lastSeen                    string
			support, repos, authors, branches int
			succ, corr, fail, hasFact         int
		)
		if err := rows.Scan(&gram, &support, &repos, &authors, &branches, &succ, &corr, &fail, &lastSeen, &hasFact); err != nil {
			return err
		}
		spec := gramSpecificity(gram, commandDF, corpusN)
		score := procedureScoreV2(support, spec, succ, corr, fail, lastSeen)
		// Procedures are diagnostic command shapes — never dossier-eligible on
		// their own (the plan: generic command loops stay visible but do not
		// become high-value candidates). Promotion happens at the task/risk layer.
		_ = hasFact
		score = applyPromotionGate(score, false)
		cluster := "procedure:\x00gram:" + gram
		if err := insertPattern(db, "procedure", repoKey, cluster, gram, "", gram, score, support, repos, authors, branches, succ, corr, fail, ts); err != nil {
			return err
		}
	}
	return rows.Err()
}

func insertRiskCandidates(db *sql.DB, repoKey string, commandDF map[string]int, corpusN int, ts string) error {
	rows, err := db.Query(`
		SELECT e.intent_sig, g.gram, COUNT(DISTINCT e.id),
		       COUNT(DISTINCT e.repo_key), COUNT(DISTINCT e.author_name), COUNT(DISTINCT e.branch),
		       SUM(e.outcome='success'), SUM(e.outcome='corrected'), SUM(e.outcome='failed'), MAX(e.created_at)
		FROM episodes e JOIN grams g ON g.episode_id = e.id
		WHERE e.outcome IN ('corrected','failed') AND e.intent_sig != ''
		GROUP BY e.intent_sig, g.gram
		HAVING COUNT(DISTINCT e.id) >= 2`)
	if err != nil {
		return err
	}
	defer rows.Close()
	for rows.Next() {
		var (
			intentSig, gram, lastSeen         string
			support, repos, authors, branches int
			succ, corr, fail                  int
		)
		if err := rows.Scan(&intentSig, &gram, &support, &repos, &authors, &branches, &succ, &corr, &fail, &lastSeen); err != nil {
			return err
		}
		spec := gramSpecificity(gram, commandDF, corpusN)
		score := riskScoreV2(support, spec, corr, fail, lastSeen)
		// Risk is its own corroboration (it IS recorded failure/correction).
		cluster := "risk:" + intentSig + "\x00gram:" + gram
		if err := insertPattern(db, "risk", repoKey, cluster, "risk: "+intentSig+" — "+gram, intentSig, gram, score, support, repos, authors, branches, succ, corr, fail, ts); err != nil {
			return err
		}
	}
	return rows.Err()
}

func insertPracticeCandidates(db *sql.DB, repoKey string, _ map[string]int, _ int, ts string) error {
	rows, err := db.Query(`
		SELECT mh.meta_id, COUNT(DISTINCT mh.episode_id),
		       COUNT(DISTINCT e.repo_key), COUNT(DISTINCT e.author_name), COUNT(DISTINCT e.branch),
		       SUM(e.outcome='success'), SUM(e.outcome='corrected'), SUM(e.outcome='failed'), MAX(e.created_at),
		       MAX(CASE WHEN EXISTS(SELECT 1 FROM episode_facts ef WHERE ef.episode_id=e.id AND ef.weight >= 2) THEN 1 ELSE 0 END)
		FROM meta_hits mh JOIN episodes e ON e.id = mh.episode_id
		GROUP BY mh.meta_id
		HAVING COUNT(DISTINCT mh.episode_id) >= 2`)
	if err != nil {
		return err
	}
	defer rows.Close()
	for rows.Next() {
		var (
			metaID, lastSeen                  string
			support, repos, authors, branches int
			succ, corr, fail, hasFact         int
		)
		if err := rows.Scan(&metaID, &support, &repos, &authors, &branches, &succ, &corr, &fail, &lastSeen, &hasFact); err != nil {
			return err
		}
		score := practiceScoreV2(support, succ, corr, repos, authors, branches, lastSeen)
		score = applyPromotionGate(score, hasFact == 1) // a way-of-working needs fact backing to promote
		cluster := "practice:" + metaID
		if err := insertPatternMeta(db, "practice", repoKey, cluster, "practice: "+metaID, metaID, score, support, repos, authors, branches, succ, corr, fail, ts); err != nil {
			return err
		}
	}
	return rows.Err()
}

// --- scoring (per docs/pattern_v2.md) ---

func supportScoreV2(support int) float64 {
	return clamp01(math.Log2(1+float64(support)) / math.Log2(31))
}
func recencyScoreV2(lastSeen string) float64 {
	t, err := time.Parse(time.RFC3339, lastSeen)
	if err != nil {
		return 0.5
	}
	days := time.Since(t).Hours() / 24
	switch {
	case days <= 30:
		return 1.0
	case days <= 90:
		return 0.6
	default:
		return 0.3
	}
}
func outcomeScoreV2(support, succ, corr, fail int) float64 {
	if support == 0 {
		return 0.5
	}
	return clamp01(0.5 + 0.5*float64(succ-corr-fail)/float64(support))
}
func diversityScoreV2(repos, authors, branches int) float64 {
	d := func(n int) float64 { return clamp01(float64(n-1) / 2.0) }
	return (d(repos) + d(authors) + d(branches)) / 3.0
}

// gramSpecificity scores how repo-distinctive a command shape is. The key fix
// over v1: it measures the rarest CONSTITUENT command's inverse document
// frequency (MAX over heads), not the gram sequence's idf. A sequence like
// "git push ▷ git status" is rare as an exact 3-command string (high sequence
// idf) yet built entirely from generic commands — measuring per-command idf and
// taking the max keeps it low, while a shape containing a genuinely rare command
// ("mise deploy", "goose up") scores high. This is what holds generic git/review
// loops below promotionSpecFloor.
func gramSpecificity(gram string, commandDF map[string]int, corpusN int) float64 {
	if corpusN == 0 {
		return 0
	}
	maxIDF := math.Log(float64(corpusN))
	if maxIDF == 0 {
		return 0
	}
	best := 0.0
	for _, head := range strings.Split(gram, gramSep) {
		head = strings.TrimSpace(head)
		if head == "" {
			continue
		}
		df := commandDF[head]
		if df == 0 {
			df = 1
		}
		if idf := math.Log(float64(corpusN) / float64(df)); idf > best {
			best = idf
		}
	}
	return clamp01(best / maxIDF)
}

func taskScoreV2(support int, spec float64, succ, corr, fail, repos, authors, branches int, lastSeen string) float64 {
	return 0.35*supportScoreV2(support) + 0.10*recencyScoreV2(lastSeen) +
		0.25*spec + 0.20*outcomeScoreV2(support, succ, corr, fail) + 0.10*diversityScoreV2(repos, authors, branches)
}
func procedureScoreV2(support int, spec float64, succ, corr, fail int, lastSeen string) float64 {
	return 0.30*supportScoreV2(support) + 0.10*recencyScoreV2(lastSeen) + 0.25*spec + 0.20*outcomeScoreV2(support, succ, corr, fail) + 0.15*0
}
func riskScoreV2(support int, spec float64, corr, fail int, lastSeen string) float64 {
	rate := 1.0 // these episodes are by definition corrected/failed
	if support == 0 {
		rate = 0
	}
	_ = corr
	_ = fail
	return 0.30*supportScoreV2(support) + 0.30*rate + 0.20*spec + 0.20*recencyScoreV2(lastSeen)
}
func practiceScoreV2(support, succ, corr, repos, authors, branches int, lastSeen string) float64 {
	return 0.30*supportScoreV2(support) + 0.20*outcomeScoreV2(support, succ, corr, 0) + 0.15*diversityScoreV2(repos, authors, branches) + 0.10*recencyScoreV2(lastSeen) + 0.25*0.5
}

func applyPromotionGate(score float64, corroborated bool) float64 {
	if !corroborated && score >= promotionThreshold {
		return promotionThreshold - 0.01 // visible, but not dossier-eligible without corroboration
	}
	return score
}

func strengthLabelV2(score float64) string {
	switch {
	case score >= 0.70:
		return "high"
	case score >= 0.50:
		return "medium"
	default:
		return "low"
	}
}

// --- insertion + evidence ---

func insertPattern(db *sql.DB, typ, repoKey, cluster, title, intentSig, gram string, score float64, support, repos, authors, branches, succ, corr, fail int, ts string) error {
	return insertPatternRow(db, typ, repoKey, cluster, title, intentSig, gram, "", score, support, repos, authors, branches, succ, corr, fail, ts)
}
func insertPatternMeta(db *sql.DB, typ, repoKey, cluster, title, metaID string, score float64, support, repos, authors, branches, succ, corr, fail int, ts string) error {
	return insertPatternRow(db, typ, repoKey, cluster, title, "", "", metaID, score, support, repos, authors, branches, succ, corr, fail, ts)
}

func insertPatternRow(db *sql.DB, typ, repoKey, cluster, title, intentSig, gram, metaID string, score float64, support, repos, authors, branches, succ, corr, fail int, ts string) error {
	id := "pattern:" + hexSHA(typ+"\x00repo\x00"+repoKey+"\x00\x00"+cluster)
	score = math.Round(score*1000) / 1000
	if _, err := db.Exec(`INSERT INTO patterns
		(id, type, scope, repo_key, workspace, cluster_key, title, intent_sig, gram, meta_id, strength, strength_label, support,
		 n_repos, n_authors, n_branches, outcome_success, outcome_corrected, outcome_neutral, outcome_failed, fingerprint, status, created_at, updated_at)
		VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,
		id, typ, "repo", repoKey, "", cluster, redactText(title), intentSig, gram, metaID, score, strengthLabelV2(score), support,
		repos, authors, branches, succ, corr, 0, fail, hexSHA(cluster+strconv.Itoa(support)), "active", ts, ts,
	); err != nil {
		return err
	}
	return insertPatternEvidence(db, id, typ, intentSig, gram, metaID)
}

// insertPatternEvidence links the top supporting episodes (corrected/failed
// first, then successful, then recent) with their source spans.
func insertPatternEvidence(db *sql.DB, patternID, typ, intentSig, gram, metaID string) error {
	var (
		q    string
		args []any
	)
	switch typ {
	case "task", "risk":
		q = `SELECT e.id, e.outcome, e.source_path, e.start_line, e.end_line FROM episodes e
		     JOIN grams g ON g.episode_id=e.id WHERE e.intent_sig=? AND g.gram=?`
		args = []any{intentSig, gram}
	case "procedure":
		q = `SELECT e.id, e.outcome, e.source_path, e.start_line, e.end_line FROM episodes e
		     JOIN grams g ON g.episode_id=e.id WHERE g.gram=?`
		args = []any{gram}
	case "practice":
		q = `SELECT e.id, e.outcome, e.source_path, e.start_line, e.end_line FROM episodes e
		     JOIN meta_hits mh ON mh.episode_id=e.id WHERE mh.meta_id=?`
		args = []any{metaID}
	default:
		return nil
	}
	q += ` ORDER BY CASE e.outcome WHEN 'corrected' THEN 0 WHEN 'failed' THEN 1 WHEN 'success' THEN 2 ELSE 3 END, e.created_at DESC LIMIT 3`
	rows, err := db.Query(q, args...)
	if err != nil {
		return err
	}
	defer rows.Close()
	rank := 0
	type ev struct {
		id, outcome, path string
		start, end        int
	}
	var evs []ev
	for rows.Next() {
		var e ev
		if err := rows.Scan(&e.id, &e.outcome, &e.path, &e.start, &e.end); err != nil {
			return err
		}
		evs = append(evs, e)
	}
	rows.Close()
	for _, e := range evs {
		if _, err := db.Exec(`INSERT OR IGNORE INTO pattern_evidence (pattern_id, episode_id, rank, outcome, source_path, start_line, end_line) VALUES (?,?,?,?,?,?,?)`,
			patternID, e.id, rank, e.outcome, e.path, e.start, e.end); err != nil {
			return err
		}
		rank++
	}
	return nil
}

// loadCommandDF returns per-command document frequency: how many distinct
// episodes ran each command head. Drives gramSpecificity's per-command idf.
func loadCommandDF(db *sql.DB) map[string]int {
	out := map[string]int{}
	rows, err := db.Query(`SELECT head, COUNT(DISTINCT episode_id) FROM episode_commands GROUP BY head`)
	if err != nil {
		return out
	}
	defer rows.Close()
	for rows.Next() {
		var h string
		var n int
		if rows.Scan(&h, &n) == nil {
			out[h] = n
		}
	}
	return out
}

func corpusScalar(db *sql.DB, q string, args ...any) int {
	var n int
	if err := db.QueryRow(q, args...).Scan(&n); err != nil {
		return 0
	}
	return n
}
